version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server

    ports:
    - "6379:6379"

    volumes:
      - ./docker-volumes/redis/data/:/var/lib/redis
      - ./docker-volumes/redis/config/redis.conf/:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

  redis-springboot:
    build: .
    mem_limit: 500M
    mem_reservation: 100M
    cpus: 0.8

    ports:
      - "8080:8080"

    links:
      - redis