server:
  port: 8080

spring:
  redis:
    host: redis
    port: 6379
    password: sOmE_sEcUrE_pAsS
    jedis:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 30
        min-idle: 10